version: "3.8"
services:
    node:
        image: "node:14-alpine"
        user: "node"
        working_dir: /home/node/app
        environment:
          - NODE_ENV=development
        volumes:
          - ./:/home/node/app
        ports:
          - "8081:8081"
        command: "npm start"
